name: powersync_flutter_demo
description: PowerSync Flutter Demo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  powersync: ^0.1.1-preview.2
  path_provider: ^2.0.12
  flutter_secure_storage: ^8.0.0
  faker_dart: ^0.1.11
  path: ^1.8.2
  sqlite3: ^1.9.1
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
